export {default as Electric} from "./Electric"
export {default as HodovayaFix} from "./HodovayaFix"
export {default as AutoDiagnostic} from "./AutoDiagnostic"
export {default as TehService} from "./TehService"
export {default as OtherServices} from "./OtherServices"
export {default as Contacts} from "./Contacts"